In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,num = 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
np.linspace(0,10,num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
len(np.linspace(0,10,num=11))

11

In [26]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [27]:
np.random.rand(1)

array([0.88814028])

In [29]:
np.random.rand(2,3)

array([[0.22763466, 0.73863439, 0.17315273],
       [0.72551996, 0.46923705, 0.42739175]])

In [30]:
np.random.randn(2)

array([-0.57143971,  0.47347911])

In [31]:
np.random.randn(2,3)

array([[ 0.03663771,  0.06012399, -1.9134445 ],
       [-0.39029118, -0.81521321, -1.09746915]])

In [38]:
np.random.randint(0,10,5)

array([3, 0, 3, 5, 6])

In [39]:
np.random.randint(0,101,(5,5))

array([[49, 68, 26, 57, 47],
       [11, 57, 11, 85,  6],
       [69, 73, 13, 81, 31],
       [38, 63, 62, 29, 19],
       [39, 13, 51,  8, 46]])

In [46]:
# By seeting seed same random values will be returned 
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [49]:
np.random.randn(4)

array([-0.46341769, -0.46572975,  0.24196227, -1.91328024])

In [50]:
np.random.randn(4)

array([-1.72491783, -0.56228753, -1.01283112,  0.31424733])

In [51]:
arr = np.arange(0,25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranintarr = np.random.randint(0,101,100)

In [55]:
ranintarr

array([ 91,  59,  79,  14,  61,  61,  46,  61,  50,  54,  63,   2, 100,
        50,   6,  20,  72,  38,  17,   3,  88,  59,  13,   8,  89,  52,
         1,  83,  91,  59,  70,  43,   7,  46,  34,  77,  80,  35,  49,
         3,   1,   5,  53,   3,  53,  92,  62,  17,  89,  43,  33,  73,
        61,  99,  13,  94,  47,  14,  71,  77,  86,  61,  39,  84,  79,
        81,  52,  23,  25,  88,  59,  40,  28,  14,  44,  64,  88,  70,
         8,  87,   0,   7,  87,  62,  10,  80,   7,  34,  34,  32,   4,
        40,  27,   6,  72,  71,  11,  33,  32,  47])

In [56]:
ranintarr.max()

100

In [57]:
ranintarr.min()

0

In [58]:
ranintarr.argmax()

12

In [59]:
ranintarr.argmin()

80

In [60]:
ranintarr.dtype

dtype('int32')

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr.shape

(25,)

In [63]:
arr = arr.reshape(5,5)

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr.shape

(5, 5)