In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_array = arr[0:5]

In [14]:
slice_of_array

array([0, 1, 2, 3, 4])

In [15]:
slice_of_array[:] = 99

In [16]:
slice_of_array

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d.shape

(3, 3)

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [22]:
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[1][1]

25

In [24]:
arr_2d[1,1]

25

In [25]:
arr_2d[0,2]

15

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [28]:
arr = np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr.shape

(10,)

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [52]:
dice_rolls.shape

(29,)

In [53]:
bool_arr1 = dice_rolls > 2

In [54]:
bool_arr1

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [56]:
len(bool_arr1)

29

In [58]:
total_rolls_over_two = list(bool_arr1)

In [60]:
total_rolls_over_two.count(True)

19